# うまくいかないので、dockerfile作ってpidファイルがなかったら作りつつ、write権限つける感じにする。
# その上でyamlを編集する

services:
  redis-master:
    build:
      context: .
      dockerfile: docker/redis-master.Dockerfile
    ports:
      - 6379:6379
    expose:
      - 6379

  redis-replica:
    build:
      context: .
      dockerfile: docker/redis-replica.Dockerfile
    ports:
      - 6380:6379
    expose:
      - 6379